"""
logo_domains.py — ticker -> primary company domain, for logo fetching.

EDITABLE. Internationals map to the PARENT company's primary domain (the ADR/local
listing shares the parent brand). Used by fetch_logos.py to download a favicon/logo mark
once into dashboard/logos/{TICKER}.png. Correct any domain here and re-run the fetch.
"""
from __future__ import annotations

TICKER_DOMAINS: dict[str, str] = {
    # --- internationals (18) -> parent primary domain ---
    "000660.KS": "skhynix.com",
    "005930.KS": "samsung.com",
    "6758.T": "sony.com",
    "7203.T": "toyota.com",
    "8306.T": "mufg.jp",
    "ASML.AS": "asml.com",
    "AZN.L": "astrazeneca.com",
    "HSBA.L": "hsbc.com",
    "NOVN.SW": "novartis.com",
    "NOVO-B.CO": "novonordisk.com",
    "RY.TO": "rbc.com",
    "SAN.MC": "santander.com",
    "SAP.DE": "sap.com",
    "SHEL.L": "shell.com",
    "SHOP.TO": "shopify.com",
    "SIE.DE": "siemens.com",
    "TD.TO": "td.com",
    "TSM": "tsmc.com",
    # --- US (71) ---
    "AAPL": "apple.com",
    "ABBV": "abbvie.com",
    "ABT": "abbott.com",
    "ACN": "accenture.com",
    "AMAT": "appliedmaterials.com",
    "AMD": "amd.com",
    "AMGN": "amgen.com",
    "AMZN": "amazon.com",
    "APH": "amphenol.com",
    "APP": "applovin.com",
    "AVGO": "broadcom.com",
    "AXP": "americanexpress.com",
    "BA": "boeing.com",
    "BAC": "bankofamerica.com",
    "BKNG": "bookingholdings.com",
    "BLK": "blackrock.com",
    "BRK-B": "berkshirehathaway.com",
    "C": "citigroup.com",
    "CAT": "caterpillar.com",
    "COST": "costco.com",
    "CRM": "salesforce.com",
    "CSCO": "cisco.com",
    "CVX": "chevron.com",
    "DIS": "disney.com",
    "GE": "geaerospace.com",
    "GOOGL": "google.com",
    "GS": "goldmansachs.com",
    "HD": "homedepot.com",
    "IBM": "ibm.com",
    "INTC": "intel.com",
    "INTU": "intuit.com",
    "ISRG": "intuitive.com",
    "JNJ": "jnj.com",
    "JPM": "jpmorganchase.com",
    "KLAC": "kla.com",
    "KO": "coca-cola.com",
    "LIN": "linde.com",
    "LLY": "lilly.com",
    "LRCX": "lamresearch.com",
    "MA": "mastercard.com",
    "MCD": "mcdonalds.com",
    "META": "meta.com",
    "MRK": "merck.com",
    "MS": "morganstanley.com",
    "MSFT": "microsoft.com",
    "MU": "micron.com",
    "NEE": "nexteraenergy.com",
    "NFLX": "netflix.com",
    "NOW": "servicenow.com",
    "NVDA": "nvidia.com",
    "ORCL": "oracle.com",
    "PEP": "pepsico.com",
    "PG": "pg.com",
    "PLTR": "palantir.com",
    "PM": "pmi.com",
    "QCOM": "qualcomm.com",
    "RTX": "rtx.com",
    "SCHW": "schwab.com",
    "SPGI": "spglobal.com",
    "T": "att.com",
    "TJX": "tjx.com",
    "TMO": "thermofisher.com",
    "TSLA": "tesla.com",
    "TXN": "ti.com",
    "UBER": "uber.com",
    "UNH": "unitedhealthgroup.com",
    "V": "visa.com",
    "VZ": "verizon.com",
    "WFC": "wellsfargo.com",
    "WMT": "walmart.com",
    "XOM": "exxonmobil.com",
}
